"""empty message

Revision ID: 2335bdf88b0a
Revises: 
Create Date: 2024-08-17 07:43:25.863034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2335bdf88b0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Nama', sa.Text(), nullable=False),
    sa.Column('Umur', sa.Integer(), nullable=True),
    sa.Column('Pekerjaan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
