"""empty message

Revision ID: d9ddc9c3e9d4
Revises: 2335bdf88b0a
Create Date: 2024-08-20 08:12:51.138102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ddc9c3e9d4'
down_revision = '2335bdf88b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.Column('Role', sa.String(), nullable=True),
    sa.Column('deskripsi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Nama', sa.TEXT(), nullable=False),
    sa.Column('Umur', sa.INTEGER(), nullable=True),
    sa.Column('Pekerjaan', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
